theme: minima
name: Technology-Methodology
title: Technology-Methodology

minima:
  social_links:
    twitter: thfranz
    github: thomasfranz    
    linkedin: thomas-franz
  show_excerpts: true
  header_pages:
  - about.md
  - portfolio.md
