theme: minima
name: Technology-Methodology
title: Technology-Methodology

minima:
  show_excerpts: true
  header_pages:
  - about.md
  - portfolio.md

social_links:
  twitter: 
    username: thfranz
  github: 
    username: thomasfranz    
  linkedin: 
    username: thomas-franz
