theme: minima
name: Technology-Methodology
title: Technology-Methodology
author: 
  name: "Thomas Franz"
  email: "thomas.franz@hs-duesseldorf.de"

page_excerpts: true

minima:
  show_excerpts: true

header_pages:
  - about.md
  - teaching.md
  - research.md
  - portfolio.md
  - blog_archive.md

social_links:
  twitter: 
    username: thfranz
  github: 
    username: thomasfranz    
  linkedin: 
    username: thomas-franz

# Minima social links
twitter_username: thfranz
github_username: thomasfranz
linkedin_username: thomas-franz